{% set name = "metaphlan" %}
{% set version = "3.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  # url: https://github.com/biobakery/MetaPhlAn/archive/{{version}}.tar.gz
  # sha256: 6249bf67f9e5a1a1264020bb0de689a17402606ada8134fb09ab416981d4a48b
  # git_url: https://github.com/biobakery/MetaPhlAn.git
  # git_rev: 19b67841cc78bb7f01e67b3eb0eadc0898e4fa9e
  path: ..

build:
  noarch: python
  script: {{ PYTHON }} setup.py biocondainstall

requirements:
  host:
    - python >=3
    - pip
    - cython
    - numpy
  run:
    - python >=3
    - bowtie2 >=2.0.0
    - dendropy
    - cython
    - numpy
    - biom-format
    - matplotlib-base
    - msgpack-python
    - biopython
    - pandas
    - scipy
    - requests
    - blast >=2.6.0
    - muscle >=3.8.1551
    - pysam >=0.8.3
    - raxml >=8.2.10
    - samtools >=0.1.19,<1.0

test:
  commands:
    - metaphlan -v
    - strainphlan -h
    - extract_markers.py -h
    - merge_metaphlan_tables.py -h
    - read_fastx.py -h

about:
  home: https://github.com/biobakery/metaphlan
  license: MIT License
  license_family: MIT
  license_file: license.txt
  summary: Metagenomic Phylogenetic Analysis
  description: |
    MetaPhlAn is a computational tool for profiling the composition of microbial
    communities (Bacteria, Archaea and Eukaryotes) from metagenomic
    shotgun sequencing data with species level resolution. From version 2.0
    MetaPhlAn is also able to identify specific strains (in the not-so-frequent
    cases in which the sample contains a previously sequenced strains) and to
    track strains across samples for all species.
